"""add cpe match cache

Revision ID: 2ceff432bf3b
Revises: 5f52d8fc4170
Create Date: 2026-08-08 07:23:19.786496

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ceff432bf3b'
down_revision: str | Sequence[str] | None = '5f52d8fc4170'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpe_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_key', sa.String(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('cpe23_uri', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('matched_version', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpe_matches_id'), 'cpe_matches', ['id'], unique=False)
    op.create_index(op.f('ix_cpe_matches_product'), 'cpe_matches', ['product'], unique=False)
    op.create_index(op.f('ix_cpe_matches_software_key'), 'cpe_matches', ['software_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpe_matches_software_key'), table_name='cpe_matches')
    op.drop_index(op.f('ix_cpe_matches_product'), table_name='cpe_matches')
    op.drop_index(op.f('ix_cpe_matches_id'), table_name='cpe_matches')
    op.drop_table('cpe_matches')
    # ### end Alembic commands ###
