"""add endpoint os_name

Revision ID: 49dede842bc0
Revises: d19923787d3c
Create Date: 2026-08-16 18:46:12.210635

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '49dede842bc0'
down_revision: str | Sequence[str] | None = 'd19923787d3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('os_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'os_name')
    # ### end Alembic commands ###
