"""add telemetry history and task output

Revision ID: 5f52d8fc4170
Revises: 54051441fb77
Create Date: 2026-08-08 07:20:37.591917

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5f52d8fc4170'
down_revision: str | Sequence[str] | None = '54051441fb77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('ram_usage', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['endpoints.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_history_device_id'), 'telemetry_history', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_history_id'), 'telemetry_history', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_history_recorded_at'), 'telemetry_history', ['recorded_at'], unique=False)
    op.add_column('task_queue', sa.Column('output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_queue', 'output')
    op.drop_index(op.f('ix_telemetry_history_recorded_at'), table_name='telemetry_history')
    op.drop_index(op.f('ix_telemetry_history_id'), table_name='telemetry_history')
    op.drop_index(op.f('ix_telemetry_history_device_id'), table_name='telemetry_history')
    op.drop_table('telemetry_history')
    # ### end Alembic commands ###
