"""add deployment ring and task target

Revision ID: 70619f51ec4c
Revises: a05659848a32
Create Date: 2026-08-17 15:21:28.117713

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70619f51ec4c'
down_revision: str | Sequence[str] | None = 'a05659848a32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('deployment_ring', sa.String(), nullable=True))
    op.create_index(op.f('ix_endpoints_deployment_ring'), 'endpoints', ['deployment_ring'], unique=False)
    op.add_column('task_queue', sa.Column('target', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Endpoint.deployment_ring's default is applied by SQLAlchemy on INSERT,
    # so it does not reach rows that already exist.
    op.execute(
        "UPDATE endpoints SET deployment_ring = 'Test-Ring' WHERE deployment_ring IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_queue', 'target')
    op.drop_index(op.f('ix_endpoints_deployment_ring'), table_name='endpoints')
    op.drop_column('endpoints', 'deployment_ring')
    # ### end Alembic commands ###
