"""add reboot status and pending updates

Revision ID: a05659848a32
Revises: 49dede842bc0
Create Date: 2026-08-16 19:28:18.200838

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a05659848a32'
down_revision: str | Sequence[str] | None = '49dede842bc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kb', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('current_version', sa.String(), nullable=True),
    sa.Column('available_version', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['endpoints.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_updates_device_id'), 'pending_updates', ['device_id'], unique=False)
    op.create_index(op.f('ix_pending_updates_id'), 'pending_updates', ['id'], unique=False)
    op.create_index(op.f('ix_pending_updates_source'), 'pending_updates', ['source'], unique=False)
    op.add_column('endpoints', sa.Column('reboot_required', sa.Boolean(), nullable=True))
    op.add_column('endpoints', sa.Column('reboot_reasons', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'reboot_reasons')
    op.drop_column('endpoints', 'reboot_required')
    op.drop_index(op.f('ix_pending_updates_source'), table_name='pending_updates')
    op.drop_index(op.f('ix_pending_updates_id'), table_name='pending_updates')
    op.drop_index(op.f('ix_pending_updates_device_id'), table_name='pending_updates')
    op.drop_table('pending_updates')
    # ### end Alembic commands ###
