"""add cve findings cache

Revision ID: c4321924d5a5
Revises: 70619f51ec4c
Create Date: 2026-08-21 21:27:59.289250

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4321924d5a5'
down_revision: str | Sequence[str] | None = '70619f51ec4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_key', sa.String(), nullable=True),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('published', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('match_mode', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cve_findings_cve_id'), 'cve_findings', ['cve_id'], unique=False)
    op.create_index(op.f('ix_cve_findings_id'), 'cve_findings', ['id'], unique=False)
    op.create_index(op.f('ix_cve_findings_software_key'), 'cve_findings', ['software_key'], unique=False)
    op.add_column('cpe_matches', sa.Column('cve_scanned_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpe_matches', 'cve_scanned_at')
    op.drop_index(op.f('ix_cve_findings_software_key'), table_name='cve_findings')
    op.drop_index(op.f('ix_cve_findings_id'), table_name='cve_findings')
    op.drop_index(op.f('ix_cve_findings_cve_id'), table_name='cve_findings')
    op.drop_table('cve_findings')
    # ### end Alembic commands ###
