"""add endpoint department

Revision ID: d19923787d3c
Revises: daa9d3746674
Create Date: 2026-08-15 12:43:18.188243

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd19923787d3c'
down_revision: str | Sequence[str] | None = 'daa9d3746674'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('department', sa.String(), nullable=True))
    op.create_index(op.f('ix_endpoints_department'), 'endpoints', ['department'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_department'), table_name='endpoints')
    op.drop_column('endpoints', 'department')
    # ### end Alembic commands ###
