"""add device token auth

Revision ID: daa9d3746674
Revises: 2ceff432bf3b
Create Date: 2026-08-15 12:22:44.753294

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'daa9d3746674'
down_revision: str | Sequence[str] | None = '2ceff432bf3b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('token_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_endpoints_token_hash'), 'endpoints', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_token_hash'), table_name='endpoints')
    op.drop_column('endpoints', 'token_hash')
    # ### end Alembic commands ###
